# Generated by Django 5.2.6 on 2025-09-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='ModulosVisibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Módulo Visible',
                'verbose_name_plural': 'Módulos Visibles',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ServicioUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servicio UE',
                'verbose_name_plural': 'Servicios UE',
            },
        ),
        migrations.CreateModel(
            name='TipoComputadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Computadora',
                'verbose_name_plural': 'Tipos de Computadora',
            },
        ),
        migrations.CreateModel(
            name='TipoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Garantía',
                'verbose_name_plural': 'Tipos de Garantía',
            },
        ),
        migrations.CreateModel(
            name='UnidadAsistencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unidad Asistencial',
                'verbose_name_plural': 'Unidades Asistenciales',
            },
        ),
        migrations.CreateModel(
            name='UnidadEjecutora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ue', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número UE')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unidad Ejecutora',
                'verbose_name_plural': 'Unidades Ejecutoras',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'unique_together': {('nombre', 'fabricante')},
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('visibilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modulosvisibles', verbose_name='Visibilidad')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.servicioue', verbose_name='Servicio')),
                ('unidad_asistencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.unidadasistencial', verbose_name='Unidad Asistencial')),
                ('unidad_ejecutora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadejecutora', verbose_name='Unidad Ejecutora')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(editable=False, verbose_name='Fecha de Finalización de Garantía')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
                ('tipo_computadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipocomputadora', verbose_name='Tipo de Computadora')),
                ('tipo_garantia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía')),
            ],
            options={
                'verbose_name': 'Computadora',
                'verbose_name_plural': 'Computadoras',
                'ordering': ['nombre'],
            },
        ),
    ]
