# Generated by Django 5.2.6 on 2025-09-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadejecutora',
            name='numero_ue',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número UE'),
        ),
    ]
