# Generated by Django 5.2.6 on 2025-09-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_unidadejecutora_numero_ue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugares',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='lugares',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='lugares',
            name='direccion',
        ),
        migrations.AddField(
            model_name='lugares',
            name='nombre_ue',
            field=models.CharField(default=1, editable=False, max_length=200, verbose_name='Nombre UE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugares',
            name='numero_ue',
            field=models.CharField(default=1, editable=False, max_length=50, verbose_name='Número UE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lugares',
            name='nombre',
            field=models.CharField(editable=False, max_length=400, unique=True, verbose_name='Nombre (generado automáticamente)'),
        ),
    ]
