# Generated by Django 5.2.6 on 2025-09-08 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_lugares_ciudad_remove_lugares_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Impresora',
                'verbose_name_plural': 'Tipos de Impresora',
            },
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(editable=False, verbose_name='Fecha de Finalización de Garantía')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
                ('tipo_garantia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía')),
                ('tipo_impresora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoimpresora', verbose_name='Tipo de Impresora')),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
                'ordering': ['nombre'],
            },
        ),
    ]
