# Generated by Django 5.2.6 on 2025-09-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_tipomonitor_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='direccion_mac',
            field=models.CharField(blank=True, help_text='Formato: AA:BB:CC:DD:EE:FF', max_length=17, null=True, verbose_name='Dirección MAC'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='valor_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición'),
        ),
    ]
