# Generated by Django 5.2.6 on 2025-09-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_computadora_direccion_ip_computadora_direccion_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='valor_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('registro', 'Registro Inicial'), ('servicio_garantia', 'Servicio por Garantía'), ('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparación'), ('cambio_estado', 'Cambio de Estado'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('asignacion_personal', 'Asignación de Personal'), ('baja', 'Baja del Equipo'), ('actualizacion', 'Actualización de Datos'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Evento')),
                ('tipo_dispositivo', models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor')], max_length=20, verbose_name='Tipo de Dispositivo')),
                ('dispositivo_id', models.PositiveIntegerField(verbose_name='ID del Dispositivo')),
                ('dispositivo_nombre', models.CharField(max_length=200, verbose_name='Nombre del Dispositivo')),
                ('descripcion', models.TextField(verbose_name='Descripción del Evento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('usuario_responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario Responsable')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['tipo_dispositivo', 'dispositivo_id'], name='inventario__tipo_di_2c8fe5_idx'), models.Index(fields=['fecha_evento'], name='inventario__fecha_e_7cef8b_idx'), models.Index(fields=['tipo_evento'], name='inventario__tipo_ev_f082f6_idx')],
            },
        ),
    ]
