# Generated by Django 5.2.6 on 2025-09-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_impresora_valor_adquisicion_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para identificar la plantilla', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la plantilla', null=True, verbose_name='Descripción')),
                ('tipo_dispositivo', models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor')], max_length=20, verbose_name='Tipo de Dispositivo')),
                ('anos_garantia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de Garantía')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('direccion_mac', models.CharField(blank=True, max_length=17, null=True, verbose_name='Dirección MAC')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que creó la plantilla')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estado', verbose_name='Estado')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.fabricante', verbose_name='Fabricante')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lugares', verbose_name='Lugar')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.modelo', verbose_name='Modelo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
                ('tipo_computadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.tipocomputadora', verbose_name='Tipo de Computadora')),
                ('tipo_garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.tipogarantia', verbose_name='Tipo de Garantía')),
                ('tipo_impresora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.tipoimpresora', verbose_name='Tipo de Impresora')),
                ('tipo_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.tipomonitor', verbose_name='Tipo de Monitor')),
            ],
            options={
                'verbose_name': 'Plantilla de Dispositivo',
                'verbose_name_plural': 'Plantillas de Dispositivos',
                'ordering': ['tipo_dispositivo', 'nombre'],
                'unique_together': {('nombre', 'tipo_dispositivo')},
            },
        ),
    ]
