# Generated by Django 5.2.6 on 2025-09-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_plantilladispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='impresoras_vinculadas',
            field=models.ManyToManyField(blank=True, help_text='Impresoras asociadas a esta computadora', related_name='computadoras_vinculadas', to='inventario.impresora', verbose_name='Impresoras Vinculadas'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='monitores_vinculados',
            field=models.ManyToManyField(blank=True, help_text='Monitores asociados a esta computadora', related_name='computadoras_vinculadas', to='inventario.monitor', verbose_name='Monitores Vinculados'),
        ),
    ]
