# Generated by Django 5.2.6 on 2025-09-25 13:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_computadora_impresoras_vinculadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numero', models.CharField(max_length=60, unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('emitido_por', models.CharField(blank=True, max_length=150)),
                ('lugar_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_destino', to='inventario.lugares')),
                ('lugar_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_origen', to='inventario.lugares')),
            ],
            options={
                'verbose_name': 'Factura de Activos',
                'verbose_name_plural': 'Facturas de Activos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='FacturaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_activo', models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor')], max_length=20)),
                ('activo_id', models.PositiveIntegerField()),
                ('numero_serie', models.CharField(max_length=200)),
                ('nombre_activo', models.CharField(max_length=400)),
                ('estado_previo', models.CharField(blank=True, max_length=120)),
                ('lugar_previo', models.CharField(blank=True, max_length=250)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='inventario.factura')),
            ],
            options={
                'verbose_name': 'Activo facturado',
                'verbose_name_plural': 'Activos facturados',
                'ordering': ['factura', 'tipo_activo', 'numero_serie'],
                'unique_together': {('factura', 'tipo_activo', 'activo_id')},
            },
        ),
    ]
