# Generated by Django 5.2.6 on 2025-10-12 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_factura_facturaactivo'),
    ]

    operations = [
        # Eliminar la tabla Lugares antigua
        migrations.DeleteModel(
            name='Lugares',
        ),

        # Crear el modelo TipoNivel
        migrations.CreateModel(
            name='TipoNivel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('nombre', models.CharField(
                    max_length=100,
                    unique=True,
                    verbose_name='Nombre del Tipo de Nivel'
                )),
                ('nivel', models.PositiveIntegerField(
                    help_text='1 = Nivel superior, 2-7 = Niveles inferiores',
                    verbose_name='Nivel Jerárquico'
                )),
                ('descripcion', models.TextField(
                    blank=True,
                    null=True,
                    verbose_name='Descripción'
                )),
                ('requiere_codigo', models.BooleanField(
                    default=False,
                    help_text='Si este nivel requiere un código identificador',
                    verbose_name='Requiere Código'
                )),
                ('activo', models.BooleanField(
                    default=True,
                    verbose_name='Activo'
                )),
            ],
            options={
                'verbose_name': 'Tipo de Nivel',
                'verbose_name_plural': 'Tipos de Nivel',
                'ordering': ['nivel', 'nombre'],
                'unique_together': {('nombre', 'nivel')},
            },
        ),

        # Crear el nuevo modelo Lugares jerárquico
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('nombre', models.CharField(
                    max_length=200,
                    verbose_name='Nombre del Lugar'
                )),
                ('codigo', models.CharField(
                    blank=True,
                    help_text='Código identificador del lugar (ej: número UE)',
                    max_length=50,
                    null=True,
                    verbose_name='Código'
                )),
                ('nombre_completo', models.CharField(
                    editable=False,
                    max_length=500,
                    verbose_name='Nombre Completo (Ruta Jerárquica)'
                )),
                ('nivel', models.PositiveIntegerField(
                    editable=False,
                    help_text='Nivel en la jerarquía (1-7)',
                    verbose_name='Nivel'
                )),
                ('ruta_jerarquica', models.TextField(
                    editable=False,
                    help_text='Almacena la ruta completa de IDs: /1/5/12/',
                    verbose_name='Ruta Jerárquica'
                )),
                ('comentarios', models.TextField(
                    blank=True,
                    null=True,
                    verbose_name='Comentarios'
                )),
                ('activo', models.BooleanField(
                    default=True,
                    verbose_name='Activo'
                )),
                ('fecha_creacion', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Fecha de Creación'
                )),
                ('fecha_modificacion', models.DateTimeField(
                    auto_now=True,
                    verbose_name='Fecha de Modificación'
                )),
                ('padre', models.ForeignKey(
                    blank=True,
                    help_text='Lugar jerárquico superior',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='hijos',
                    to='inventario.lugares',
                    verbose_name='Lugar Padre'
                )),
                ('tipo_nivel', models.ForeignKey(
                    help_text='Tipo de nivel jerárquico de este lugar',
                    on_delete=django.db.models.deletion.PROTECT,
                    to='inventario.tiponivel',
                    verbose_name='Tipo de Nivel'
                )),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['nivel', 'nombre'],
            },
        ),

        # Crear índices
        migrations.AddIndex(
            model_name='lugares',
            index=models.Index(
                fields=['nivel'],
                name='inventario__nivel_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='lugares',
            index=models.Index(
                fields=['padre'],
                name='inventario__padre_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='lugares',
            index=models.Index(
                fields=['tipo_nivel'],
                name='inventario__tipo_ni_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='lugares',
            index=models.Index(
                fields=['ruta_jerarquica'],
                name='inventario__ruta_je_idx'
            ),
        ),
    ]
