# Generated by Django 4.2.7 on 2025-10-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_rebuild_lugares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('punto_reorden', models.PositiveIntegerField(default=0)),
                ('unidad_medida', models.CharField(default='unidad', max_length=50)),
                ('valor_unitario_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitario Estimado')),
                ('activo', models.BooleanField(default=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Finalización de Garantía')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('direccion_mac', models.CharField(blank=True, help_text='Formato: AA:BB:CC:DD:EE:FF', max_length=17, null=True, verbose_name='Dirección MAC')),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Versión de Firmware')),
                ('cantidad_puertos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puertos Disponibles')),
                ('soporte_poe', models.BooleanField(default=False, verbose_name='Soporte PoE')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo de Networking',
                'verbose_name_plural': 'Equipos de Networking',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Finalización de Garantía')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('tipo_conexion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Conexión')),
                ('es_inalambrico', models.BooleanField(default=False, verbose_name='¿Es inalámbrico?')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periférico',
                'verbose_name_plural': 'Periféricos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_licencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número de Licencia')),
                ('cantidad_licencias', models.PositiveIntegerField(default=1)),
                ('licencias_en_uso', models.PositiveIntegerField(default=0)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Total')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Telefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Finalización de Garantía')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('extension_interna', models.CharField(blank=True, max_length=20, null=True, verbose_name='Extensión Interna')),
                ('numero_linea', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Línea')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('direccion_mac', models.CharField(blank=True, max_length=17, null=True, verbose_name='Dirección MAC')),
                ('tipo_conexion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Conexión')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo de Telefonía',
                'verbose_name_plural': 'Dispositivos de Telefonía',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('unidad_medida_default', models.CharField(default='unidad', max_length=50, verbose_name='Unidad de Medida Predeterminada')),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Insumo',
                'verbose_name_plural': 'Tipos de Insumo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoNetworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo de Networking',
                'verbose_name_plural': 'Tipos de Equipos de Networking',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPeriferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Periférico',
                'verbose_name_plural': 'Tipos de Periférico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Software',
                'verbose_name_plural': 'Tipos de Software',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTelefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo de Telefonía',
                'verbose_name_plural': 'Tipos de Dispositivos de Telefonía',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameIndex(
            model_name='lugares',
            new_name='inventario__nivel_d69d02_idx',
            old_name='inventario__nivel_idx',
        ),
        migrations.RenameIndex(
            model_name='lugares',
            new_name='inventario__padre_i_c0e52b_idx',
            old_name='inventario__padre_idx',
        ),
        migrations.RenameIndex(
            model_name='lugares',
            new_name='inventario__tipo_ni_2b6d6e_idx',
            old_name='inventario__tipo_ni_idx',
        ),
        migrations.RenameIndex(
            model_name='lugares',
            new_name='inventario__ruta_je_6a2287_idx',
            old_name='inventario__ruta_je_idx',
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('networking', 'Networking'), ('telefonia', 'Telefonía'), ('periferico', 'Periférico'), ('insumo', 'Insumo'), ('software', 'Software')], max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Lugar jerárquico superior (dejar vacío para nivel raíz)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='inventario.lugares', verbose_name='Lugar Padre'),
        ),
        migrations.AlterField(
            model_name='plantilladispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('networking', 'Networking'), ('telefonia', 'Telefonía'), ('periferico', 'Periférico'), ('insumo', 'Insumo'), ('software', 'Software')], max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='tipo_garantia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='tipo_telefonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipotelefonia', verbose_name='Tipo de Telefonía'),
        ),
        migrations.AddField(
            model_name='software',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='software',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='software',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lugares', verbose_name='Lugar asociado'),
        ),
        migrations.AddField(
            model_name='software',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='software',
            name='tipo_software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tiposoftware', verbose_name='Tipo de Software'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='tipo_garantia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='tipo_periferico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoperiferico', verbose_name='Tipo de Periférico'),
        ),
        migrations.AddField(
            model_name='networking',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='networking',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='networking',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='networking',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='networking',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='networking',
            name='tipo_garantia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía'),
        ),
        migrations.AddField(
            model_name='networking',
            name='tipo_networking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tiponetworking', verbose_name='Tipo de Equipo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoinsumo', verbose_name='Tipo de Insumo'),
        ),
    ]
