# Generated by Django 5.2.6 on 2025-10-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_insumo_networking_periferico_software_telefonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='moneda',
            field=models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='impresora',
            name='moneda',
            field=models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='moneda',
            field=models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='networking',
            name='moneda',
            field=models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='moneda',
            field=models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='moneda',
            field=models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda'),
        ),
    ]
