# Generated by Django 5.2.6 on 2025-10-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_computadora_moneda_impresora_moneda_monitor_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='moneda',
            field=models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='software',
            name='moneda',
            field=models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda'),
        ),
    ]
