# Generated by Django 5.2.6 on 2025-10-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_insumo_moneda_software_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilladispositivo',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición'),
        ),
    ]
