# Generated by Django 5.2.6 on 2025-10-31 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_rename_almacen_to_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTecnologiaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tecnología Médica',
                'verbose_name_plural': 'Tipos de Tecnología Médica',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('networking', 'Networking'), ('telefonia', 'Telefonía'), ('periferico', 'Periférico'), ('tecnologia_medica', 'Tecnología Médica'), ('insumo', 'Insumo'), ('software', 'Software')], max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AlterField(
            model_name='facturaactivo',
            name='tipo_activo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('tecnologia_medica', 'Tecnología Médica'), ('insumo', 'Insumo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plantilladispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('networking', 'Networking'), ('telefonia', 'Telefonía'), ('periferico', 'Periférico'), ('tecnologia_medica', 'Tecnología Médica'), ('insumo', 'Insumo'), ('software', 'Software')], max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.CreateModel(
            name='TecnologiaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('numero_activo_fijo', models.CharField(blank=True, help_text='Código de activo fijo contable', max_length=100, null=True, verbose_name='Número de Activo Fijo')),
                ('registro_sanitario', models.CharField(blank=True, help_text='Número de registro ante autoridad sanitaria', max_length=100, null=True, verbose_name='Registro Sanitario')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Finalización de Garantía')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('moneda', models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda')),
                ('requiere_calibracion', models.BooleanField(default=False, verbose_name='Requiere Calibración Periódica')),
                ('frecuencia_calibracion_meses', models.PositiveIntegerField(blank=True, help_text='Cada cuántos meses requiere calibración', null=True, verbose_name='Frecuencia de Calibración (meses)')),
                ('fecha_ultima_calibracion', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Calibración')),
                ('requiere_mantenimiento_preventivo', models.BooleanField(default=True, verbose_name='Requiere Mantenimiento Preventivo')),
                ('frecuencia_mantenimiento_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia de Mantenimiento (meses)')),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Último Mantenimiento')),
                ('clasificacion_riesgo', models.CharField(blank=True, choices=[('clase_i', 'Clase I - Riesgo Bajo'), ('clase_iia', 'Clase IIa - Riesgo Medio'), ('clase_iib', 'Clase IIb - Riesgo Medio-Alto'), ('clase_iii', 'Clase III - Riesgo Alto'), ('clase_iv', 'Clase IV - Riesgo Muy Alto')], help_text='Clasificación según normativa médica', max_length=20, null=True, verbose_name='Clasificación de Riesgo')),
                ('area_aplicacion', models.CharField(blank=True, help_text='Ej: UCI, Quirófano, Emergencia, etc.', max_length=200, null=True, verbose_name='Área de Aplicación')),
                ('requiere_personal_especializado', models.BooleanField(default=False, verbose_name='Requiere Personal Especializado')),
                ('voltaje_operacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Voltaje de Operación')),
                ('potencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Potencia')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
                ('tipo_garantia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía')),
                ('tipo_tecnologia_medica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipotecnologiamedica', verbose_name='Tipo de Equipo Médico')),
            ],
            options={
                'verbose_name': 'Tecnología Médica',
                'verbose_name_plural': 'Tecnología Médica',
                'ordering': ['nombre'],
            },
        ),
    ]
