# Generated by Django 5.2.6 on 2025-10-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_tipotecnologiamedica_alter_bitacora_tipo_dispositivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Orden')),
                ('tipo_servicio', models.CharField(choices=[('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_correctivo', 'Mantenimiento Correctivo'), ('reparacion', 'Reparación'), ('calibracion', 'Calibración'), ('instalacion', 'Instalación'), ('actualizacion', 'Actualización'), ('diagnostico', 'Diagnóstico'), ('limpieza', 'Limpieza'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Servicio')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('en_espera_repuesto', 'En Espera de Repuesto'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('tipo_dispositivo', models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('networking', 'Networking'), ('telefonia', 'Telefonía'), ('periferico', 'Periférico'), ('tecnologia_medica', 'Tecnología Médica'), ('insumo', 'Insumo'), ('software', 'Software')], max_length=20, verbose_name='Tipo de Dispositivo')),
                ('dispositivo_id', models.PositiveIntegerField(verbose_name='ID del Dispositivo')),
                ('dispositivo_nombre', models.CharField(editable=False, max_length=200, verbose_name='Nombre del Dispositivo')),
                ('dispositivo_numero_serie', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Número de Serie')),
                ('descripcion_problema', models.TextField(verbose_name='Descripción del Problema/Necesidad')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('solucion_aplicada', models.TextField(blank=True, null=True, verbose_name='Solución Aplicada')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('tecnico_asignado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Técnico Asignado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización')),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de Mano de Obra')),
                ('costo_repuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de Repuestos')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Costo Total')),
                ('moneda', models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda')),
                ('repuestos_utilizados', models.TextField(blank=True, help_text='Lista de repuestos utilizados en el servicio', null=True, verbose_name='Repuestos Utilizados')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['tipo_dispositivo', 'dispositivo_id'], name='inventario__tipo_di_0373a1_idx'), models.Index(fields=['estado'], name='inventario__estado_a725c5_idx'), models.Index(fields=['prioridad'], name='inventario__priorid_712690_idx'), models.Index(fields=['tecnico_asignado'], name='inventario__tecnico_b7271f_idx'), models.Index(fields=['fecha_solicitud'], name='inventario__fecha_s_96df28_idx')],
            },
        ),
    ]
