# Generated by Django 5.2.6 on 2025-11-03 19:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_ordenservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioServicioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(max_length=60, unique=True, verbose_name='Número de Envío')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío')),
                ('motivo_envio', models.TextField(verbose_name='Motivo del Envío')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_estimada_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Retorno')),
                ('fecha_retorno_real', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Retorno')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('en_reparacion', 'En Reparación'), ('reparado', 'Reparado'), ('retornado', 'Retornado'), ('cancelado', 'Cancelado')], default='enviado', max_length=20, verbose_name='Estado')),
                ('costo_servicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo del Servicio')),
                ('moneda', models.CharField(choices=[('UYU', 'UYU'), ('USD', 'USD')], default='UYU', max_length=3, verbose_name='Moneda')),
                ('emitido_por', models.CharField(blank=True, max_length=150, verbose_name='Emitido Por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_servicio', to='inventario.proveedor', verbose_name='Proveedor de Servicio')),
            ],
            options={
                'verbose_name': 'Envío a Servicio de Proveedor',
                'verbose_name_plural': 'Envíos a Servicio de Proveedores',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='EnvioServicioActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_activo', models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('networking', 'Networking'), ('telefonia', 'Telefonía'), ('periferico', 'Periférico'), ('tecnologia_medica', 'Tecnología Médica')], max_length=20, verbose_name='Tipo de Activo')),
                ('activo_id', models.PositiveIntegerField(verbose_name='ID del Activo')),
                ('numero_serie', models.CharField(max_length=200, verbose_name='Número de Serie')),
                ('nombre_activo', models.CharField(max_length=400, verbose_name='Nombre del Activo')),
                ('estado_previo', models.CharField(blank=True, max_length=120, verbose_name='Estado Previo')),
                ('lugar_previo', models.CharField(blank=True, max_length=250, verbose_name='Lugar Previo')),
                ('problema_reportado', models.TextField(blank=True, verbose_name='Problema Reportado')),
                ('diagnostico_proveedor', models.TextField(blank=True, verbose_name='Diagnóstico del Proveedor')),
                ('reparacion_realizada', models.TextField(blank=True, verbose_name='Reparación Realizada')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='inventario.envioservicioproveedor', verbose_name='Envío')),
            ],
            options={
                'verbose_name': 'Activo en Servicio',
                'verbose_name_plural': 'Activos en Servicio',
                'ordering': ['envio', 'tipo_activo', 'numero_serie'],
                'unique_together': {('envio', 'tipo_activo', 'activo_id')},
            },
        ),
    ]
