# Generated by Django 6.0.1 on 2026-02-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_envioservicioproveedor_envioservicioactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Herramienta',
                'verbose_name_plural': 'Tipos de Herramienta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Mobiliario',
                'verbose_name_plural': 'Tipos de Mobiliario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('networking', 'Networking'), ('telefonia', 'Telefonía'), ('periferico', 'Periférico'), ('tecnologia_medica', 'Tecnología Médica'), ('insumo', 'Insumo'), ('software', 'Software'), ('mobiliario', 'Mobiliario'), ('vehiculo', 'Vehículo'), ('herramienta', 'Herramienta')], max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('networking', 'Networking'), ('telefonia', 'Telefonía'), ('periferico', 'Periférico'), ('tecnologia_medica', 'Tecnología Médica'), ('insumo', 'Insumo'), ('software', 'Software'), ('mobiliario', 'Mobiliario'), ('vehiculo', 'Vehículo'), ('herramienta', 'Herramienta')], max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Finalización de Garantía')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('moneda', models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda')),
                ('requiere_calibracion', models.BooleanField(default=False, verbose_name='Requiere Calibración')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
                ('tipo_garantia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía')),
                ('tipo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoherramienta', verbose_name='Tipo de Herramienta')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Finalización de Garantía')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('moneda', models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda')),
                ('material', models.CharField(blank=True, help_text='Ej: madera, metal, vidrio, plástico', max_length=100, null=True, verbose_name='Material')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
                ('tipo_garantia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía')),
                ('tipo_mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipomobiliario', verbose_name='Tipo de Mobiliario')),
            ],
            options={
                'verbose_name': 'Mobiliario',
                'verbose_name_plural': 'Mobiliario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie / VIN')),
                ('numero_inventario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario')),
                ('matricula', models.CharField(help_text='Matrícula o patente del vehículo', max_length=20, unique=True, verbose_name='Matrícula')),
                ('anio_fabricacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Fabricación')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('anos_garantia', models.PositiveIntegerField(help_text='Número de años de garantía', verbose_name='Años de Garantía')),
                ('fecha_finalizacion_garantia', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Finalización de Garantía')),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Adquisición')),
                ('moneda', models.CharField(choices=[('UYU', 'Pesos Uruguayos ($)'), ('USD', 'Dólares (US$)'), ('EUR', 'Euros (€)')], default='UYU', max_length=3, verbose_name='Moneda')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.fabricante', verbose_name='Fabricante / Marca')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lugares', verbose_name='Lugar')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo', verbose_name='Modelo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
                ('tipo_garantia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipogarantia', verbose_name='Tipo de Garantía')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipovehiculo', verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['nombre'],
            },
        ),
    ]
